### ISSUE TITLE
과제1 - 2차 테스트 (10월 29일 화요일)

### ISSUE THREAD

**Issue by dawit0905** [shinkeonkim/EurekaProject-Xycar-5#2]
# 정리
속도가 변경 될 때, 경계값을 그대로 유지 하고 다른 값을 변경할 지, 경계 값을 수정할지 판단.
전체적인 안정도는 많이 올라옴. 
 - 후진 3회, 전진 1,2회는 정확
 - 전진 3회는 때에 따라 다름.
 - 마지막 테스트때 55점 획득함.

### 필터 
평균값 필터보다 중간값 필터가 비교적 깔끔함.
중간값 필터로 갈 거같음.

### 바퀴 조향각
테스트할 때 마다 바퀴 조향각이 이상해짐. 개선 필요. 

# 테스트 
중간값 필터: 초음파 센서의 값을 일정이상 리스트로 받아서, 정렬된 리스트의 중간값으로 판단.
평균값 필터: 초음파 센서의 값을 큐(FIFO)방식으로 5개

경계 값이 높을 수록 거리가 멀다. 
경계 값이 낮을 수록 거리가 가깝다.

## 1차
전진: 중간값 필터 사용
후진: 중간값 필터 사용

전진 속도 값: 110, 120, 130
전진 거리 경계 값: 40, 40, 40

후진 속도 값: 70
후진 거리 경계 값: 40

전진 속도 값 130일 때, 충돌 사고 있었음. - 속도가 증가 됐을 때에 경계 값 수정 필요.

## 2차
전진: 평균값 필터 사용
후진: 중간값 필터 사용

전진 속도 값: 110, 120, 130
전진 거리 경계 값: 40, 50, 60

후진 속도 값: 70
후진 거리 경계 값: 40

전진 속도 값 130일 때, 충돌 사고 있었음. - 속도가 증가 됐을 때에 개선 필요.
전진 속도가 증가 될때, 경계 값을 변경해줬지만(더 크게 해줬지만) 더 가까워졌음. 개선 필요. 

## 3차
전진: 중간값 필터 사용
후진: 중간값 필터 사용

전진 속도 값: 110, 120, 130
전진 거리 경계 값: 40, 60, 80

후진 속도 값: 70
후진 거리 경계 값: 40

전진 속도 값 130일 때, 충돌 사고 있었다. - 속도가 증가 됐을 때에 개선 필요

계속해서 속도가 증가 됐을 때 충돌 사고가 있다.
초음파 경계 값을 올려서 멈추는 타이밍을 빠르게 하거나, 
바퀴 모터 제어를 해야 될 거같다.

## 4차
전진: 중간값 필터 사용
후진: 중간값 필터 사용

전진 속도 값: 110, 120, 130
전진 거리 경계 값: 40, 70, 90

후진 속도 값: 70
후진 거리 경계 값: 40

이번에는 전진 속도 값이 130일 때 +-5cm에 제대로 멈춤.

## 5차
전진: 중간값 필터 사용
후진: 중간값 필터 사용

전진 속도 값: 105, 112, 119
전진 거리 경계 값: 38, 40, 70

후진 속도 값: 70
후진 거리 경계 값: 40

## 6차
전진: 중간값 필터 사용
후진: 중간값 필터 사용

전진 속도 값: 110, 116, 122
전진 거리 경계 값: 40, 50, 75

후진 속도 값: 70
후진 거리 경계 값: 40

5,6차 콜백 사용했는데 망함.

## 7차
전진: 중간값 필터 사용
후진: 중간값 필터 사용

전진 속도 값: 110, 117, 123
전진 거리 경계 값: 40, 50, 60

후진 속도 값: 70
후진 거리 경계 값: 40

## 8차
전진: 중간값 필터 사용
후진: 중간값 필터 사용

전진 속도 값: 110, 117, 123
전진 거리 경계 값: 40, 50, 64

후진 속도 값: 70
후진 거리 경계 값: 43

**Comment by shinkeonkim** [comment]
complete
