### ISSUE TITLE
과제1 - 3차 테스트 + 추가사항 (10월 30일 수요일)

### ISSUE THREAD

**Issue by gomtang3274** [shinkeonkim/EurekaProject-Xycar-5#3]
# 기본설정
중간값 필터: 초음파 센서의 값을 큐(FIFO)방식으로 5개
전진속도(임계값): 110(40) 117(50) 123(64)
후진속도(임계값): 70(43)

## 1차
변경사항)
- 10Hz를 100Hz로 변경

감상평)
- 속도가 가장 빠를 때(123) 멈추는 구간이 들쑥날쑥함

## 2차
변경사항)
- 전진 임계값 변경 35 45 55

감상평)
- 100Hz는 포기

## 3차
변경사항)
- 초반 중간값필터 값 5개 받고 시작

감상평)
- 점수 10 / 10 / 7 / 10 / 5 / 10    52점
- 후진은 80%정도 정화성
- 제일 빠를 때의 멈추는 구간 들쭉날쭉

## 4차
 변경사항)
- while순환문 내에  print(front/back 리스트) 추가

감상평)
- Xycar 모터 작동 안함 -> 모터 충전 필요

## 5차
변경사항)
-  100Hz로 변경
- callback에서 front와 back에 append
- 임계값 변경 40 55 70

감상평)
- .

## 6차
변경사항)
- print문으로 중간값 필터 혹인

감상평)
- .

## 7차
변경사항)
- 전진속도 변경 100 110 120

감상평)
- 100은 속도가 안되는 걸로

## 8차
변경사항)
- 전진속도 변경 110 115 120
- 전진 임계값 변경 55 65 80

감상평)
- 후진 값 조정필요
- 전진 값 세번째 조정필요

## 9차
변경사항)
- 후진 임계값 53 변경

감상평)
- .

## 10차
변경사항)
- 전진 임계값 변경 50 65 80
- 후진 임계값 변경 58

감상평)
- 첫 번째 전진이 너무 가까움
- 후진이 너무 빨리 멈추는 듯

## 11차
변경사항)
- 전진 임계값 변경 48 65 80
- 후진 임계값 변경 56

감상평)
- 세 번째 전진 착지 지점이 들쭉날쭉함
- 후진이 불안정함
 

## 12차
변경사항)
- 세 번쨰 전진 시 역주행(1초) 걸어줌

감상평)
- 세 번째 여전히 들쭉날쭉
- 후진이 살짝 불안정함 널럴한 느낌

## 13차
변경사항)
- 강의 노트에 있는 방향 전환 for loop 과 정지를 5초동안하는 코드의 순서를 변경함.
- 역주행 삭제

감상평)
- 관성(반동) 없어짐 ( 멈출 때 바로 멈춤)
- 임계값 변경 필요

## 14차
변경사항)
- 세 번째 전진 임계값 변경 83

감상평)
- 후진 불안정
- 관성이 없을 때 멈추는 과정이 미묘함

## 15차
변경사항)
- 후진 관성 제어 (속도 110)
-  세 번째 전진 임계값 85
- 후진 임계값 54

감상평)

**Comment by shinkeonkim** [comment]
complete
