### ISSUE TITLE
과제2 - 1차테스트(11월 21일 목요일/유레카)

### ISSUE THREAD

**Issue by gomtang3274** [shinkeonkim/EurekaProject-Xycar-5#4]
# 정리
유레카프로젝트 및 창업연계공학설계입문 Xycar의 극좌표계에 따른 theta의 값 적용

# 테스트 
- 극좌표계

## 1차
- 변수 사용 갯수
ㄴ angle, speed(2개)

- angle 조정 상수
음수값: 1.6
양수값: 1.75

- speed 조정 식
speed = K - min(abs(theta)/2,10)

- 목적
차량의 이탈을 막기 위한 시도

- 문제점
영상에서 직선을 검출하지 못할 경우, 이전에 저장되어있는 세타를 이용하게끔 적용하였으나, 오히려 이탈 현상이 급증함

## 2차
- 변수 사용 갯수
ㄴ angle, speed(2개)

- angle 조정 상수
음수값: 1.6
양수값: 1.75

- speed 조정 식
speed = K - min(abs(theta)/2,10)

- 목적
차선의 중앙 위치로 주행하기 위한 시도

- 문제점
차량이 주행 중 직진마다 차량의 진행 방향이 왼쪽으로 치우치는 현상

- 해결방안
1) Xycar 본래의 오프셋에 따른 운명
2) 코드 중 steer 메써드의 k * theta 의 과정을 theta가 특정 구간(직진)일 경우 단순무식하게 0을 곱하는 방식을 적용

## 3차
- 변수 사용 갯수
ㄴ angle, speed(2개)

- angle 조정 상수
음수값: 1.6
양수값: 1.75
theta가 특정 구간(-1<theta<1): 0

- speed 조정 식
speed = K - min(abs(theta)/2,10)

- 노드의 순환 주기
rate(10) -> rate(100) 변경

- 목적
차량의 주행방향 조정을 위한 시도

- 문제점
노드의 순환 주기 변경으로 인해, theta의 값이 0인 상황의 출현 빈도가 급증

## 4차
- 변수 사용 갯수
ㄴ angle, speed(2개)

- angle 조정 상수
음수값: 1.6
양수값: 1.75
theta가 특정 구간(-1<theta<1): 0

- speed 조정 식
speed = K - min(abs(theta)/2,10)

- 노드의 순환 주기
rate(100) -> rate(10) 변경

- 목적
노드의 순환주기 변경한 후 실행 확인

- 문제점

## 5차

- 코드 추가
변수 추가 left, right
가중치 추가 diff 추가

## 6차
- 변수 사용 갯수
ㄴ angle, speed, left, right(4개)

- angle 조정 상수
음수값: 변경예정
양수값:  변경예정
theta가 특정 구간(-1<theta<1): 0

- speed 조정 식
speed = K - min(abs(theta)/2,10)

- 노드의 순환 주기
rate(100) -> rate(10) 변경

- diff 범위 변경
|diff| < 3 -> |diff| < 1

- weight 가중치 변경
-5, 5 -> -10, 10

- 목적
노드의 순환주기 변경한 후 실행 확인

- 문제점

## 7차

- 1차와 동일한 코드로 변경

- 문제점
구불구불한 구간에서 차선 인식 불가

## 8차
- 6차와 유사한 코드로 변경

- 변수 사용 갯수
ㄴ angle, speed, left, right(4개)

- angle 조정 상수
음수값: 변경예정
양수값:  변경예정
theta가 특정 구간(-1<theta<1): 0

- speed 조정 식
speed = K - min(abs(theta)/2,10)

- 노드의 순환 주기
rate(100) -> rate(10) 변경

- diff 값 변경
diff = 55 - mid -> diff = 50-mid

- 직진 각도 변경
92도

- 목적
노드의 순환주기 변경한 후 실행 확인

- 문제점

## 9차

- 속도 조절 방해 원인 발견
(speed + 90)

- 문제점
너무 큰 가중치 부여
너무 저조한 속도

## 10차

- 속도
120 -> 130 변경

## 11차

- weight 가중치 변경
10 10으로 변경

- angle 조정 상수
양쪽: 1.5 -> 1.25 변경

- 문제점
차선이 한쪽 상실 시, K와 Weight의 이중으로 작용하였기에, 비교적 너무 큰값이 회전으로 작용

## 12차

- weight와 angle 조정 상수 k 상호작용
차선을 한쪽을 상실할 경우, weight의 미적용으로 변경

## final

- angle 조정 상수
왼쪽: 1.75
오른쪽: 1.5
- speed
130 시작 + 수식
- weight 전체 미적용

- 직진 각도
92.5
- theta 판단
-3 < theta<3

**Comment by shinkeonkim** [comment]
complete
