### ISSUE TITLE
과제2 - 2차테스트(11월 22일 금요일/유레카)

### ISSUE THREAD

**Issue by gomtang3274** [shinkeonkim/EurekaProject-Xycar-5#5]
# 정리
유레카프로젝트 및 창업연계공학설계입문 Xycar의 극좌표계에 따른 theta의 값 적용

# 테스트 
- 극좌표계

## 1차
- 변수 사용 갯수
ㄴ angle, speed(2개)

- angle 조정 상수
(-0.8, 0.8) K = 0
(-5, 5) K =1.3
(-10 10) K = 1.5
그외 1,75

- speed 조정 식
speed = K - min(abs(theta)/2,10)

- 목적

- 문제점
구불구불한 구간에서 회전을 인식못하고 직진하는 상황 발생

## 2차

- angle 조정 상수
(-0.8, 0.8) K = 1
(-5, 5) K =1.3
(-10 ,10) K = 1.5
그외 1,75

- 직진 시 각 변경
93로 변경

## 3차 
- angel조정 상수
(theta <-10)K = 1.6으로 변경

- LineDetector 임계치 상수 변경: 50
하얀색 선인지 판단하는 상수역할, 초기값: 100

## 4차
- LineDetector 임계치 상수 변경: 80

## 5차
- autodrive 코드 직진 없이 좌,우회전 반복

## 6차
- 변수 4개
- autodrive 
(-0.8, 0.8) K = 1
(-5, 5) K =1.3
(-10 ,10) K = 1.6 ,1.75
(theta < =-10) K =1.6
그 외 =1.5

- 직선 주행 시, 가중치 사용 곡선 주행 시 theta값 사용

## 7차
- LinerDetetor right:93 -> right:90 으로 변경
- 문제점: 너무 왼쪽으로 편향되어 주행한다.

## 8차
- autodrive 가중치 weigth:15->  weight:10으로 변경 
- 문제점: Xycar가 직선으로 가는 도중에도 왼쪽으로 꺾는다.

## 9차
- autodrive theta 구간 변경
(-20,20)K=1.6
(theta>=20)K=1.75
(theta<=-20)K=1.6
그 외 = 1.5

## 10차
- autodrive theta 구간 변경, K값 변경
(-5,5)K=2.5
(15,15)K=1.5
(-20,20)K=1.7
(theta>=20)K=1.75
(theta<=-20)K=1.6
그 외 = 1.5

## 11차
- autodrive  직진 값 91.8변경, K값 변경
(-4,4)K=2.5
(-20,20)K=1.5
(theta>=20)K=2.0
(theta<=-20)K=2.5
그 외 = 1.5

## 12차
- autodrive K값 변경
(-4,4)K=2.5
(-20,20)K=1.5
(theta>=20)K=2.2
(theta<=-20)K=2.7
그 외 = 1.5

## 13차
- autodrive K값 변경, 속도 변경
theta&K값 12차와 동일
속도 값:130 -> 140으로 조정

- 문제점:속도가 너무 빨라서 Xycar가 탈선함.

## 14차
- autodrive K값 변경, 속도 변경
(-4,4)K=2.5
(-20,20)K=1.5
(theta>=20)K=2.3
(theta<=-20)K=2.8
그 외 = 1.5
속도 값 : 다시 130으로 변경

-문제점:Xycar가 너무 왼쪽으로 치우쳐짐.

## 15차
- autodrive K값 변경
(-0.8,0.8)K=1.4
(-4,4)K=2.5
(-20,20)K=1.5
(theta>=20)K=2.3
(theta<=-20)K=2.8
그 외 = 1.5

## 16차
- autodrive K값 변경
(-0.8,0.8)K=3.0
(-4,4)K=2.5
(-20,20)K=1.5
(theta>=20)K=2.3
(theta<=-20)K=2.8
그 외 = 1.5

## 17차
- autodrive K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(-20,20)K=1.5
(theta>=20)K=2.3
(theta<=-20)K=3.0
그 외 = 1.5

## 18차
- autodrive theta&K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(-15,15)K=2.0
(theta>=20)K=2.3
(theta<=-20)K=3.0
그 외 = 1.5

## 19차
- autodrive theta&K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(-15,15)K=1.75
(theta>=20)K=2.3
(theta<=-20)K=3.0
그 외 = 1.5

## 20차
- linedetector 코드 수정
- 우회전 시, filter 이용해 theta 값의 변화 속도를 느리게 받아오도록 함.
- autodrive K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=3.0
그 외 = 1.5

## 21차
- linedetector theta 값의 변화 속도를 20차시보다 조금 빠르게 받아오도록 함.

## 22차
- 좌회전 시, Angle 조정 상수를 낮춤.
- theta 변화 속도를 20 & 21차시의 중간값으로 수정함.
- autodrive K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=2.0
그 외 = 1.5

## 23차
- autodrive K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=2.3
그 외 = 1.5

## 24차
- autodrive K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=2.15
그 외 = 1.5

## 25차
- autodrive K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=2.1
그 외 = 1.5

## 26차
- autodrive K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(4,15)K=1.75
(-15,-4)K=2.0
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=2.1
그 외 = 1.5

## 27차
- autodrive K값 변경
(-0.8,0.8)K=5.0
(-4,4)K=2.5
(4,15)K=1.75
(-15,-4)K=1.86
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=2.1
그 외 = 1.5

## 28차
- autodrive K값 변경
(-0.8,0.8)K=8.0
(-4,4)K=2.5
(4,15)K=1.75
(-15,-4)K=1.8
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=2.1
그 외 = 1.5

## 29차
- autodrive K값 변경
(-0.8,0.8)K=8.0
(-4,4)K=2.5
(4,15)K=1.75
(-15,-4)K=1.86
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=1.7
그 외 = 1.5

## 30차
- autodrive K값 변경
(-0.8,0)K=8
(0,0.8)K=15
(-4,4)K=2.5
(4,15)K=1.75
(-15,-4)K=1.86
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=2.1
그 외 = 1.5

## 31차
- 직진 시 91.8값을 92.0으로 수정

## 32차
- linedetector theta 값의 변화 속도를 조금 더 느리게 받아오도록 함.
- 직진 시 92.0을 91.8로 다시 수정

## 33차시
- autodrive K값 변경
(-0.8,0)K=8
(0,0.8)K=15
(-4,4)K=2.5
(4,15)K=1.75
(-15,-4)K=1.86
(-15,15)K=1.75
(theta>=20)K=3.0
(theta<=-20)K=1.8
그 외 = 1.5

## 34차
- theta의 절댓값이 감소할 때는 변화율이 느리지만 theta 의 절댓값이 커지면 변화율이 커짐

**Comment by shinkeonkim** [comment]
complete
