### ISSUE TITLE
과제2 - 1차테스트(12월 4일/창연공)

### ISSUE THREAD

**Issue by gomtang3274** [shinkeonkim/EurekaProject-Xycar-5#6]
# 1차 
###  obs = 70
-  주행에는 큰 무리가 없으나 마지막 정차 구간에서 충돌

# 2차
### obs = 85
- 4~5회 정차해버림

# 3차
### 속도 = 140
- (120,60,?) 들어와서 주행 중 원치 않는 정차
- 초음파 센서 값이 50 -> 80 으로 껑충 뛰는 현상 발견

# 4차
### 정차 시, 장애물 실존 여부에 따른 정차 시간 고려
- 튀는 값 1회 정차, 사람 5회 정차, 장애물 1회 정차
- 총 90초 주행

# 5차
### 4차 재시도
- 총 1분 8초 ~ 4초 주행
-  튀는 값 3회 정차, 사람 1회 정차

# 6차
### 우회전 최초 시 이후부터 초음파 정지 적용
- 주행 시 문제 해결됨
- 총 62초 주행
- 문제: 정차 시에, 일정시간 정차후 다시 주행하는 문제

# 7차

### 정차시 autodirve.py 종료
- 문제 해결

**Comment by shinkeonkim** [comment]
complete
